name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ggingmin-ct/test
          stage: main
          yaml: |
            name: springboot-api
            app: java@11
            options:
              ports: 8080
              env:
                - name: DB_HOST
                  value: mariadb
                - name: DB_PORT
                  value: "3306"
                - name: DB_NAME
                  value: testdb
                - name: DB_USERNAME
                  value: root
                - name: DB_PASSWORD
                  value: root
                - name: SPRING_PROFILES_ACTIVE
                  value: staging
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
